Repository spart-final-team4/HowManySet, pull requests merged in 2025-06, with the labels that each got.

#7 Feature/#4
  HowManySet.xcodeproj/project.pbxproj
  HowManySet/Data/Model/UserSettingDTO.swift
  HowManySet/Data/Model/WorkoutDTO.swift
  HowManySet/Data/Model/WorkoutRecordDTO.swift
  HowManySet/Data/Model/WorkoutRoutineDTO.swift
  HowManySet/Data/Model/WorkoutSetDTO.swift
  HowManySet/Data/Repositories/RecordRepositoryImpl.swift
  HowManySet/Data/Repositories/RoutineRepositoryImpl.swift
  HowManySet/Domain/Entity/UserSetting.swift
  HowManySet/Domain/Entity/Workout.swift
  HowManySet/Domain/Entity/WorkoutRecord.swift
  HowManySet/Domain/Entity/WorkoutRoutine.swift
  HowManySet/Domain/Entity/WorkoutSession.swift
  HowManySet/Domain/Entity/WorkoutSet.swift
  HowManySet/Domain/Protocols/Record/FetchRecordUseCaseProtocol.swift
  HowManySet/Domain/Protocols/Record/SaveRecordUseCaseProtocol.swift
  HowManySet/Domain/Protocols/Routine/DeleteRoutineUseCaseProtocol.swift
  HowManySet/Domain/Protocols/Routine/FetchRoutineUseCaseProtocol.swift
  HowManySet/Domain/Protocols/Routine/SaveRoutineUseCaseProtocol.swift
  HowManySet/Domain/Protocols/UserPage/FetchUserSettingUseCaseProtocol.swift
  HowManySet/Domain/Protocols/UserPage/SaveUserSettingUseCaseProtocol.swift
  HowManySet/Domain/Repositories/RecordRepository.swift
  HowManySet/Domain/Repositories/RoutineRepository.swift
  HowManySet/Domain/Repositories/UserSettingRepository.swift
  HowManySet/Domain/UseCase/Record/FetchRecordUseCase.swift
  HowManySet/Domain/UseCase/Record/SaveRecordUseCase.swift
  HowManySet/Domain/UseCase/Routine/DeleteRoutineUseCase.swift
  HowManySet/Domain/UseCase/Routine/FetchRoutineUseCase.swift
  HowManySet/Domain/UseCase/Routine/SaveRoutineUseCase.swift
  HowManySet/Domain/UseCase/UserPage/FetchUserSettingUseCase.swift
  HowManySet/Domain/UseCase/UserPage/SaveUserSettingUseCase.swift
  HowManySetTests/Record/FetchRecordUseCaseTests.swift
  HowManySetTests/Record/SaveRecordUseCaseTests.swift
  HowManySetTests/Routine/DeleteRoutineUseCaseTests.swift
  HowManySetTests/Routine/FetchRoutineUseCaseTests.swift
  HowManySetTests/Routine/SaveRoutineUseCaseTests.swift
  HowManySetTests/UserPage/FetchUserSettingUseCaseTests.swift
  HowManySetTests/UserPage/SaveUserSettingUseCaseTests.swift
Labels: enhancement

#12 Feature/#10
  .github/workflows/CI.yml
  HowManySet.xcodeproj/project.pbxproj
  HowManySet.xcodeproj/xcshareddata/xcschemes/HowManySet.xcscheme
  HowManySet.xcodeproj/xcshareddata/xcschemes/HowManySetTests.xcscheme
  HowManySet/HowManySetUITests/HowManySetUITests.swift
  HowManySet/HowManySetUITests/HowManySetUITestsLaunchTests.swift
  TestPlan.xctestplan
Labels: enhancement

#17 Feature/#1
  HowManySet.xcodeproj/project.pbxproj
  HowManySet.xcodeproj/xcshareddata/xcschemes/HowManySetLiveActivityExtension.xcscheme
  HowManySet/App/Coordinator/MyPageCoordinator.swift
  HowManySet/App/Coordinator/OnBoardingCoordinator.swift
  HowManySet/App/Coordinator/TabBarCoordinator.swift
  HowManySet/Presentation/Common/Extension/Int+Extension.swift
  HowManySet/Presentation/Common/SetProgressBar.swift
  HowManySet/Presentation/Common/SetProgressBarRepresentable.swift
  HowManySet/Resources/Assets.xcassets/brand.colorset/Contents.json
  HowManySet/Resources/Assets.xcassets/brandBackground.colorset/Contents.json
  HowManySet/Resources/Info.plist
  HowManySet/Resources/Localizable.xcstrings
  HowManySetLiveActivity/AppIntent.swift
  HowManySetLiveActivity/HowManySetLiveActivity.swift
  HowManySetLiveActivity/HowManySetLiveActivityControl.swift
  HowManySetLiveActivity/HowManySetLiveActivityLiveActivity.swift
  HowManySetWidget/AppIntent/PauseRoutineIntent.swift
  HowManySetWidget/AppIntent/PlayRoutineIntent.swift
  HowManySetWidget/AppIntent/SkipRestIntent.swift
  HowManySetWidget/AppIntent/SkipSetIntent.swift
  HowManySetWidget/AppIntent/StopWorkoutIntent.swift
  HowManySetWidget/Assets.xcassets/AccentColor.colorset/Contents.json
  HowManySetWidget/Assets.xcassets/AppIcon.appiconset/Contents.json
  HowManySetWidget/Assets.xcassets/Contents.json
  HowManySetWidget/Assets.xcassets/WidgetBackground.colorset/Contents.json
  HowManySetWidget/Assets.xcassets/brand.colorset/Contents.json
  HowManySetWidget/Assets.xcassets/brandBackground.colorset/Contents.json
  HowManySetWidget/HowManySetWidgetBundle.swift
  HowManySetWidget/HowManySetWidgetInfo.plist
  HowManySetWidget/HowManySetWidgetLiveActivity.swift
Labels: enhancement

#23 Feature/#2
  HowManySet.xcodeproj/project.pbxproj
  HowManySet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  HowManySet/App/AppDelegate.swift
  HowManySet/App/Coordinator/AppCoordinator.swift
  HowManySet/App/Coordinator/AuthCoordinator.swift
  HowManySet/Presentation/Feature/Auth/AuthView.swift
  HowManySet/Presentation/Feature/Auth/AuthViewController.swift
  HowManySet/Presentation/Feature/Auth/Reactor/AuthViewReactor.swift
  HowManySet/Resources/Assets.xcassets/AppColor.colorset/Contents.json
  HowManySet/Resources/Assets.xcassets/Google.imageset/Contents.json
  HowManySet/Resources/Assets.xcassets/Google.imageset/Property 1=Icon_Google.png
  HowManySet/Resources/Assets.xcassets/Kakao.imageset/Contents.json
  HowManySet/Resources/Assets.xcassets/Kakao.imageset/Property 1=Icon, Property 2=Icon_Kakaotalk.png
  HowManySet/Resources/Assets.xcassets/MainIcon.imageset/Contents.json
  HowManySet/Resources/Assets.xcassets/MainIcon.imageset/Vector.svg
  HowManySet/Resources/GoogleService-Info.plist
  HowManySet/Resources/Info.plist
Labels: enhancement

#31 Feature/#5
  HowManySet/App/Coordinator/CalendarCoordinator.swift
  HowManySet/App/Coordinator/TabBarCoordinator.swift
  HowManySet/App/DIContainer.swift
  HowManySet/Domain/Entity/Workout.swift
  HowManySet/Domain/Entity/WorkoutRecord.swift
  HowManySet/Domain/Entity/WorkoutRoutine.swift
  HowManySet/Presentation/Common/Extension/Date+Extension.swift
  HowManySet/Presentation/Common/Extension/Int+Extension.swift
  HowManySet/Presentation/Feature/Calendar/CalendarView.swift
  HowManySet/Presentation/Feature/Calendar/CalendarViewController.swift
  HowManySet/Presentation/Feature/Calendar/Reactor/CalendarViewModel.swift
  HowManySet/Presentation/Feature/Calendar/Reactor/CalendarViewReactor.swift
  HowManySet/Presentation/Feature/Calendar/RecordCell.swift
  HowManySet/Presentation/Feature/RecordDetail/Reactor/RecordDetailViewReactor.swift
  HowManySet/Presentation/Feature/RecordDetail/RecordDetailViewController.swift
  HowManySet/Resources/Assets.xcassets/calendarArrowLeft.imageset/24 1.svg
  HowManySet/Resources/Assets.xcassets/calendarArrowLeft.imageset/24 2.svg
  HowManySet/Resources/Assets.xcassets/calendarArrowLeft.imageset/24.svg
  HowManySet/Resources/Assets.xcassets/calendarArrowLeft.imageset/Contents.json
  HowManySet/Resources/Assets.xcassets/calendarArrowRight.imageset/24 1.svg
  HowManySet/Resources/Assets.xcassets/calendarArrowRight.imageset/24 2.svg
  HowManySet/Resources/Assets.xcassets/calendarArrowRight.imageset/24.svg
  HowManySet/Resources/Assets.xcassets/calendarArrowRight.imageset/Contents.json
Labels: enhancement

#33 Feature/#22
  HowManySet/App/Coordinator/MyPageCoordinator.swift
  HowManySet/Presentation/Common/DefaultPopupViewController.swift
  HowManySet/Presentation/Feature/MyPage/MyPageViewController.swift
  HowManySet/Presentation/Feature/MyPage/Reactor/MyPageViewReactor.swift
  HowManySet/Presentation/Feature/MyPage/View/MyPageCollectionView/MyPageCollectionFooterView.swift
  HowManySet/Presentation/Feature/MyPage/View/MyPageCollectionView/MyPageCollectionHeaderView.swift
  HowManySet/Presentation/Feature/MyPage/View/MyPageCollectionView/MyPageCollectionView.swift
  HowManySet/Presentation/Feature/MyPage/View/MyPageCollectionView/MyPageCollectionViewCells/DefaultMyPageCollectionViewCell.swift
  HowManySet/Presentation/Feature/MyPage/View/MyPageCollectionView/MyPageCollectionViewCells/VersionMyPageCollectionViewCell.swift
  HowManySet/Presentation/Feature/MyPage/View/MyPageHeaderView.swift
  HowManySet/Presentation/Feature/MyPage/View/MyPageModel.swift
  HowManySet/Presentation/Feature/MyPage/View/MyPageView.swift
Labels: enhancement

#39 Feature/#32
  HowManySet/Presentation/Feature/RoutineList/Reactor/RoutineListViewReactor.swift
  HowManySet/Presentation/Feature/RoutineList/RoutineCell.swift
  HowManySet/Presentation/Feature/RoutineList/RoutineListView.swift
  HowManySet/Presentation/Feature/RoutineList/RoutineListViewController.swift
Labels: enhancement

#38 Feature/#3
  HowManySet/Presentation/Feature/Auth/AuthView.swift
  HowManySet/Presentation/Feature/Auth/AuthViewController.swift
  HowManySet/Presentation/Feature/Auth/FirestoreService.swift
Labels: 기능 구현

#54 Feature/#50
  HowManySet/App/Coordinator/RoutineListCoordinator.swift
  HowManySet/Domain/Entity/Workout.swift
  HowManySet/Domain/Entity/WorkoutRoutine.swift
  HowManySet/Domain/Entity/WorkoutSet.swift
  HowManySet/Presentation/Feature/RoutineList/Reactor/RoutineListViewReactor.swift
  HowManySet/Presentation/Feature/RoutineList/RoutineCell.swift
  HowManySet/Presentation/Feature/RoutineList/RoutineListView.swift
  HowManySet/Presentation/Feature/RoutineList/RoutineListViewController.swift
  HowManySet/Presentation/Feature/RoutineName/Reactor/RoutineNameReactor.swift
  HowManySet/Presentation/Feature/RoutineName/RoutineNameView.swift
  HowManySet/Presentation/Feature/RoutineName/RoutineNameViewController.swift
Labels: 기능 구현

#75 홈 화면 오류 수정 및 UI 기기 대응, 화면 터치시 키보드 닫기
  HowManySet/App/Coordinator/RoutineCompleteCoordinator.swift
  HowManySet/Presentation/Common/ViewAnimator/SlideUpAnimator.swift
  HowManySet/Presentation/Feature/Calendar/CalendarViewController.swift
  HowManySet/Presentation/Feature/EditExcercise/EditExcerciseViewController.swift
  HowManySet/Presentation/Feature/Home/EditAndMemoViewController.swift
  HowManySet/Presentation/Feature/Home/HomePagingCardView.swift
  HowManySet/Presentation/Feature/Home/HomeViewController.swift
  HowManySet/Presentation/Feature/Home/Reactor/HomeViewReactor.swift
  HowManySet/Presentation/Feature/Home/RestInfoView.swift
  HowManySet/Presentation/Feature/OnBoarding/OnBoardingViewController.swift
  HowManySet/Presentation/Feature/RoutineComplete/RoutineCompleteViewController.swift
  HowManySet/Presentation/Feature/RoutineName/RoutineNameViewController.swift
Labels: 기능 구현, 오류 개선

#70 Feature/#62 - 루틴 페이지 reactor, Coodinator 편집
  HowManySet/App/Coordinator/HomeCoordinator.swift
  HowManySet/App/Coordinator/RoutineListCoordinator.swift
  HowManySet/Domain/Entity/WorkoutRoutine.swift
  HowManySet/Presentation/Feature/EditExcercise/EditExcerciseContentView/EditExcerciseContentHeaderView.swift
  HowManySet/Presentation/Feature/EditExcercise/EditExcerciseContentView/EditExcerciseContentView.swift
  HowManySet/Presentation/Feature/EditExcercise/EditExcerciseContentView/EditExcerciseHorizontalContentStackView.swift
  HowManySet/Presentation/Feature/EditExcercise/EditExcerciseCurrentView/EditExcerciseCurrentStackView.swift
  HowManySet/Presentation/Feature/EditExcercise/EditExcerciseCurrentView/SavedExcerciseView.swift
  HowManySet/Presentation/Feature/EditExcercise/EditExcerciseHeaderView.swift
  HowManySet/Presentation/Feature/EditExcercise/EditExcerciseViewController.swift
  HowManySet/Presentation/Feature/EditExcercise/Reactor/EditExcerciseViewReactor.swift
  HowManySet/Presentation/Feature/Home/HomeViewController.swift
  HowManySet/Presentation/Feature/RoutineList/Reactor/RoutineListViewReactor.swift
  HowManySet/Presentation/Feature/RoutineList/RoutineListViewController.swift
  HowManySet/Presentation/Feature/RoutineName/Reactor/RoutineNameReactor.swift
  HowManySet/Presentation/Feature/RoutineName/RoutineNameView.swift
  HowManySet/Presentation/Feature/RoutineName/RoutineNameViewController.swift
Labels: 기능 구현

#86 Feature/#74 - 루틴리스트 realm 저장 확인, EditRoutineVC 리액터 연결
  HowManySet/App/Coordinator/AppCoordinator.swift
  HowManySet/App/Coordinator/HomeCoordinator.swift
  HowManySet/App/Coordinator/RoutineListCoordinator.swift
  HowManySet/Data/Repositories/RoutineRepositoryImpl.swift
  HowManySet/Presentation/Feature/EditRoutine/EditRoutineBottomSheetViewController.swift
  HowManySet/Presentation/Feature/EditRoutine/EditRoutineTableView.swift
  HowManySet/Presentation/Feature/EditRoutine/EditRoutineTableViewCell.swift
  HowManySet/Presentation/Feature/EditRoutine/EditRoutineViewController.swift
  HowManySet/Presentation/Feature/EditRoutine/Reactor/EditRoutinViewReactor.swift
  HowManySet/Presentation/Feature/EditRoutine/Reactor/EditRoutineViewReactor.swift
  HowManySet/Presentation/Feature/Home/EditAndMemoViewController.swift
  HowManySet/Presentation/Feature/RoutineList/RoutineListViewController.swift
Labels: 기능 구현, 리팩토링/구조화

#91 FirbaseAuth 리팩토링, 로그아웃,회원탈퇴 기능 구현 및 적용 + UI 개선
  HowManySet/App/AppDelegate.swift
  HowManySet/App/Coordinator/AppCoordinator.swift
  HowManySet/App/Coordinator/MyPageCoordinator.swift
  HowManySet/App/Coordinator/OnBoardingCoordinator.swift
  HowManySet/App/Coordinator/TabBarCoordinator.swift
  HowManySet/App/DIContainer.swift
  HowManySet/App/SceneDelegate.swift
  HowManySet/Data/DTO/UserDTO.swift
  HowManySet/Data/Firebase/FirebaseAuthService.swift
  HowManySet/Data/Firebase/FirebaseAuthServiceProtocol.swift
  HowManySet/Data/Firebase/Repositories/AuthRepositoryImpl.swift
  HowManySet/Domain/Entity/User.swift
  HowManySet/Domain/Repositories/AuthRepository.swift
  HowManySet/Domain/UseCase/Auth/AuthUseCase.swift
  HowManySet/Domain/UseCase/Protocols/Auth/AuthUseCaseProtocol.swift
  HowManySet/Presentation/Feature/Auth/AuthView.swift
  HowManySet/Presentation/Feature/Auth/AuthViewController.swift
  HowManySet/Presentation/Feature/Auth/Reactor/AuthViewReactor.swift
  HowManySet/Presentation/Feature/MyPage/MyPageViewController.swift
  HowManySet/Presentation/Feature/MyPage/Reactor/MyPageViewReactor.swift
  HowManySet/Presentation/Feature/OnBoarding/NicknameInputView.swift
  HowManySet/Presentation/Feature/OnBoarding/OnBoardingViewController.swift
  HowManySet/Presentation/Feature/OnBoarding/OnboardingView.swift
  HowManySet/Resources/Base.lproj/LaunchScreen.storyboard
  HowManySet/Resources/GoogleService-Info.plist
  HowManySet/Resources/Info.plist
Labels: 기능 구현, 오류 개선, 리팩토링/구조화

#104 Fix/#103 - protocol extension으로 인한 무한루프 현상 해결
  HowManySet/Domain/Repositories/WorkoutRepository.swift
  HowManySet/Domain/UseCase/Protocols/Record/DeleteAllRecordUseCaseProtocol.swift
  HowManySet/Domain/UseCase/Protocols/Record/DeleteRecordUseCaseProtocol.swift
  HowManySet/Domain/UseCase/Protocols/Record/FetchRecordUseCaseProtocol.swift
  HowManySet/Domain/UseCase/Protocols/Record/SaveRecordUseCaseProtocol.swift
  HowManySet/Domain/UseCase/Protocols/Record/UpdateRecordUseCaseProtocol.swift
  HowManySet/Domain/UseCase/Protocols/Routine/DeleteRoutineUseCaseProtocol.swift
  HowManySet/Domain/UseCase/Protocols/Routine/FetchRoutineUseCaseProtocol.swift
  HowManySet/Domain/UseCase/Protocols/Routine/SaveRoutineUseCaseProtocol.swift
  HowManySet/Domain/UseCase/Protocols/Routine/UpdateRoutineUseCaseProtocol.swift
  HowManySet/Domain/UseCase/Protocols/UserPage/FetchUserSettingUseCaseProtocol.swift
  HowManySet/Domain/UseCase/Protocols/UserPage/SaveUserSettingUseCaseProtocol.swift
  HowManySet/Domain/UseCase/Protocols/Workout/DeleteWorkoutUseCaseProtocol.swift
  HowManySet/Domain/UseCase/Protocols/Workout/UpdateWorkoutUseCaseProtocol.swift
  HowManySet/Domain/UseCase/Record/DeleteAllRecordUseCase.swift
  HowManySet/Domain/UseCase/Record/DeleteRecordUseCase.swift
  HowManySet/Domain/UseCase/Record/FetchRecordUseCase.swift
  HowManySet/Domain/UseCase/Record/SaveRecordUseCase.swift
  HowManySet/Domain/UseCase/Record/UpdateRecordUseCase.swift
  HowManySet/Domain/UseCase/Routine/DeleteRoutineUseCase.swift
  HowManySet/Domain/UseCase/Routine/FetchRoutineUseCase.swift
  HowManySet/Domain/UseCase/Routine/SaveRoutineUseCase.swift
  HowManySet/Domain/UseCase/Routine/UpdateRoutineUseCase.swift
  HowManySet/Domain/UseCase/UserPage/FetchUserSettingUseCase.swift
  HowManySet/Domain/UseCase/UserPage/SaveUserSettingUseCase.swift
  HowManySet/Domain/UseCase/Workout/DeleteWorkoutUseCase.swift
  HowManySet/Domain/UseCase/Workout/UpdateWorkoutUseCase.swift
Labels: bug, 오류 개선

#116 feat: #112 - Tabbar Heght 수정
  HowManySet/App/Coordinator/TabBarCoordinator.swift
Labels: 기능 구현, 리팩토링/구조화

#127 TestFlight 카카오 로그인 이슈
  HowManySet/App/SceneDelegate.swift
Labels: 오류 개선

#129 로그인 실패 에러 메시지에 localizedDescription이 나오는 보안 이슈
  HowManySet/Presentation/Feature/Auth/AuthViewController.swift
Labels: 변경사항

#135 NicknameInputView 버튼 가려지는 이슈
  HowManySet/Presentation/Feature/OnBoarding/NicknameInputView.swift
  HowManySet/Presentation/Feature/OnBoarding/OnBoardingViewController.swift
Labels: 기능 구현

#141 Asset 온보딩 이미지 png -> pdf
  HowManySet/Presentation/Feature/OnBoarding/OnboardingView.swift
  HowManySet/Resources/Assets.xcassets/OnboardImage/Onboard_BreakTime.imageset/Contents.json
  HowManySet/Resources/Assets.xcassets/OnboardImage/Onboard_BreakTime.imageset/Onboard_BreakTime.pdf
  HowManySet/Resources/Assets.xcassets/OnboardImage/Onboard_BreakTime.imageset/Onboard_BreakTime.png
  HowManySet/Resources/Assets.xcassets/OnboardImage/Onboard_LiveActivity.imageset/Contents.json
  HowManySet/Resources/Assets.xcassets/OnboardImage/Onboard_LiveActivity.imageset/Onboard_LiveActivity.pdf
  HowManySet/Resources/Assets.xcassets/OnboardImage/Onboard_LiveActivity.imageset/Onboard_LiveActivity.png
  HowManySet/Resources/Assets.xcassets/OnboardImage/Onboard_RoutineList.imageset/Contents.json
  HowManySet/Resources/Assets.xcassets/OnboardImage/Onboard_RoutineList.imageset/Onboard_RoutineList.pdf
  HowManySet/Resources/Assets.xcassets/OnboardImage/Onboard_RoutineList.imageset/Onboard_RoutineList.png
  HowManySet/Resources/Assets.xcassets/OnboardImage/Onboard_SetRoutine.imageset/Contents.json
  HowManySet/Resources/Assets.xcassets/OnboardImage/Onboard_SetRoutine.imageset/Onboard_SetRoutine.pdf
  HowManySet/Resources/Assets.xcassets/OnboardImage/Onboard_SetRoutine.imageset/Onboard_SetRoutine.png
  HowManySet/Resources/Assets.xcassets/OnboardImage/Onboard_Water.imageset/Contents.json
  HowManySet/Resources/Assets.xcassets/OnboardImage/Onboard_Water.imageset/Onboard_Water.pdf
  HowManySet/Resources/Assets.xcassets/OnboardImage/Onboard_Water.imageset/Onboard_Water.png
  HowManySet/Resources/Assets.xcassets/OnboardImage/Onboard_WorkOutSetting.imageset/Contents.json
  HowManySet/Resources/Assets.xcassets/OnboardImage/Onboard_WorkOutSetting.imageset/Onboard_WorkOutSetting.pdf
  HowManySet/Resources/Assets.xcassets/OnboardImage/Onboard_WorkOutSetting.imageset/Onboard_WorkOutSetting.png
Labels: 변경사항

#142 스와이프 삭제 및 업데이트 로직 구현 및 피드백 수정
  HowManySet/App/Coordinator/CalendarCoordinator.swift
  HowManySet/App/DIContainer.swift
  HowManySet/Presentation/Feature/Calendar/CalendarView.swift
  HowManySet/Presentation/Feature/Calendar/CalendarViewController.swift
  HowManySet/Presentation/Feature/Calendar/Reactor/CalendarViewReactor.swift
  HowManySet/Presentation/Feature/Calendar/RecordCell.swift
  HowManySet/Presentation/Feature/RecordDetail/Cell/MemoInfoCell.swift
  HowManySet/Presentation/Feature/RecordDetail/Cell/SummaryInfoCell.swift
  HowManySet/Presentation/Feature/RecordDetail/Cell/WorkoutDetailInfoCell.swift
  HowManySet/Presentation/Feature/RecordDetail/HeaderView/WorkoutDetailHeaderView.swift
  HowManySet/Presentation/Feature/RecordDetail/Reactor/RecordDetailViewReactor.swift
  HowManySet/Presentation/Feature/RecordDetail/RecordDetailHeaderView.swift
  HowManySet/Presentation/Feature/RecordDetail/RecordDetailView.swift
  HowManySet/Presentation/Feature/RecordDetail/RecordDetailViewController.swift
  HowManySet/Presentation/Feature/RoutineList/Reactor/RoutineListViewReactor.swift
  HowManySet/Presentation/Feature/RoutineList/RoutineCell.swift
  HowManySet/Presentation/Feature/RoutineList/RoutineListView.swift
  HowManySet/Presentation/Feature/RoutineList/RoutineListViewController.swift
  HowManySet/Presentation/Feature/RoutineName/RoutineNameViewController.swift
Labels: 변경사항, 기능 구현, 리팩토링/구조화

#137 라이브 액티비티 휴식 중 UI 변경
  HowManySetWidget/HowManySetWidgetLiveActivity.swift
  HowManySetWidget/Resources/Assets.xcassets/brandDumbbell.imageset/Contents.json
  HowManySetWidget/Resources/Assets.xcassets/brandDumbbell.imageset/Property 1=kg_52.svg
  HowManySetWidget/Resources/Assets.xcassets/waterFill.imageset/Contents.json
  HowManySetWidget/Resources/Assets.xcassets/waterFill.imageset/Property 1=Variant2.svg
Labels: 변경사항

#150 rebase 시 누락 사항 변경
  HowManySet/App/DIContainer.swift
  HowManySet/Presentation/Feature/Home/Reactor/HomeViewReactor.swift
Labels: 오류 개선

#158 로그인 화면 Loading Indicator 구현 및 적용
  HowManySet/Presentation/Feature/Auth/AuthViewController.swift
  HowManySet/Presentation/Feature/Auth/LoadingIndicator.swift
  HowManySet/Presentation/Feature/Auth/Reactor/AuthViewReactor.swift
Labels: 기능 구현

#153 코디네이터 관련 오류 해결
  HowManySet/App/Coordinator/AppCoordinator.swift
  HowManySet/App/Coordinator/EditRoutineCoordinator.swift
  HowManySet/App/Coordinator/HomeCoordinator.swift
  HowManySet/App/Coordinator/RoutineCompleteCoordinator.swift
  HowManySet/App/Coordinator/RoutineListCoordinator.swift
  HowManySet/App/Coordinator/TabBarCoordinator.swift
  HowManySet/App/DIContainer.swift
  HowManySet/Presentation/Common/Enum/ViewCaller.swift
  HowManySet/Presentation/Feature/EditRoutine/EditRoutineViewController.swift
  HowManySet/Presentation/Feature/Home/HomeViewController.swift
  HowManySet/Presentation/Feature/HomeStart/HomeRoutineStartCardView.swift
  HowManySet/Presentation/Feature/HomeStart/HomeStartViewController.swift
  HowManySet/Presentation/Feature/RoutineList/RoutineListView.swift
  HowManySet/Presentation/Feature/RoutineList/RoutineListViewController.swift
Labels: bug, 변경사항, 오류 개선

#155 휴식 관련 오류 해결, EditRoutine present시 변경
  HowManySet/App/Coordinator/EditRoutineCoordinator.swift
  HowManySet/App/Coordinator/RoutineListCoordinator.swift
  HowManySet/App/DIContainer.swift
  HowManySet/Presentation/Feature/EditRoutine/EditRoutineTableView.swift
  HowManySet/Presentation/Feature/EditRoutine/EditRoutineTableViewCell.swift
  HowManySet/Presentation/Feature/EditRoutine/EditRoutineViewController.swift
  HowManySet/Presentation/Feature/Home/HomeViewController.swift
  HowManySet/Presentation/Feature/Home/Reactor/HomeViewReactor.swift
  HowManySet/Presentation/Feature/RoutineList/RoutineListViewController.swift
Labels: 변경사항, 오류 개선

#161 온보딩 화면 iPhone SE 기기 대응 완료
  HowManySet/Presentation/Feature/OnBoarding/OnboardingView.swift
Labels: 변경사항, 오류 개선

#171 온보딩 리팩토링
  HowManySet/App/Coordinator/AppCoordinator.swift
  HowManySet/App/Coordinator/OnBoardingCoordinator.swift
  HowManySet/App/DIContainer.swift
  HowManySet/Data/Firebase/Repositories/AuthRepositoryImpl.swift
  HowManySet/Domain/UseCase/Auth/AuthUseCase.swift
  HowManySet/Domain/UseCase/Protocols/Auth/AuthUseCaseProtocol.swift
  HowManySet/Presentation/Feature/OnBoarding/OnBoardingViewController.swift
  HowManySet/Presentation/Feature/OnBoarding/Reactor/OnBoardingViewReactor.swift
Labels: 리팩토링/구조화

#167 refactor: #166 - 운동 삭제 시 루틴 삭제 및 저장 했던 로직을 운동만 삭제하도록 변경
  HowManySet/App/DIContainer.swift
  HowManySet/Presentation/Feature/EditRoutine/Reactor/EditRoutineViewReactor.swift
Labels: bug

#181 운동 중지 후 스킵 시 오류 해결
  HowManySet/Presentation/Feature/Home/Reactor/HomeViewReactor.swift
Labels: 오류 개선

#190 완료한 세트/운동종목 수 카운팅 로직 수정
  HowManySet/Presentation/Feature/Home/Reactor/HomeViewReactor.swift
  HowManySet/Presentation/Feature/RoutineComplete/RoutineCompleteViewController.swift
Labels: 오류 개선

#203 fix: #202 - 카카오 uid 이슈 해결 전까지 카카오 로그인 비활성화 (마이너 업데이트에 수정 예정)
  HowManySet/Presentation/Feature/Auth/AuthView.swift
Labels: bug, 변경사항, 기술적 의사결정

#194 백그라운드 휴식 시간 개선
  HowManySet/Presentation/Feature/Home/HomeViewController.swift
  HowManySet/Presentation/Feature/Home/Reactor/HomeViewReactor.swift
  HowManySet/Presentation/Feature/Home/RestInfoView.swift
Labels: 기능 구현, 오류 개선

#209 운동종료 버튼 클릭 시 팝업 창 취소버튼 추가
  HowManySet/App/Coordinator/HomeCoordinator.swift
  HowManySet/Presentation/Common/ExercisePopupViewController.swift
Labels: 기능 구현

#211 Fix/#205 Record Realm저장 방식 변경 / 상세기록 보기 버그 수정
  HowManySet/Data/DTO/WorkoutRecordDTO.swift
  HowManySet/Data/DTO/WorkoutRoutineDTO.swift
  HowManySet/Data/PersistentStorages/Model/RMWorkout.swift
  HowManySet/Data/PersistentStorages/Model/RMWorkoutRecord.swift
  HowManySet/Data/PersistentStorages/Model/RMWorkoutRoutine.swift
  HowManySet/Presentation/Feature/Calendar/CalendarViewController.swift
  HowManySet/Presentation/Feature/Home/Reactor/HomeViewReactor.swift
Labels: bug, 리팩토링/구조화

#216 로그인 플로우 개선/ 비회원 uid 삭제 및 플로우 수정
  HowManySet/App/Coordinator/AppCoordinator.swift
  HowManySet/App/Coordinator/MyPageCoordinator.swift
  HowManySet/App/Coordinator/OnBoardingCoordinator.swift
  HowManySet/Data/Firebase/FirebaseAuthService.swift
  HowManySet/Data/Firebase/Repositories/AuthRepositoryImpl.swift
  HowManySet/Domain/Entity/User.swift
  HowManySet/Domain/UseCase/Auth/AuthUseCase.swift
  HowManySet/Presentation/Feature/MyPage/Reactor/MyPageViewReactor.swift
  HowManySet/Presentation/Feature/OnBoarding/OnBoardingViewController.swift
  HowManySet/Presentation/Feature/OnBoarding/Reactor/OnBoardingViewReactor.swift
Labels: 변경사항, 오류 개선, 리팩토링/구조화

#221 휴식 0일 시 세트완료 오류 해결
  HowManySet/Presentation/Feature/Home/Reactor/HomeViewReactor.swift
Labels: bug

#222 AppDelegate 잘못된 화면 진입 방지 코드 추가
  HowManySet/App/AppDelegate.swift
Labels: 오류 개선
