Repository spart-final-team4/HowManySet, pull requests merged in 2025-07, with the labels that each got.

#234 개인정보처리방침 이메일 변경
  HowManySet/Resources/Privacy/privacy.html
Labels: 변경사항

#235 운동 중 메모 dismiss 시 충돌 해결
  HowManySet/Presentation/Feature/Home/Reactor/HomeViewReactor.swift
Labels: bug

#239 운동 중 메모 업데이트 오류 해결
  HowManySet/Presentation/Feature/Home/Reactor/HomeViewReactor.swift
Labels: bug

#247 마이페이지 앱 평가하기, 버전정보 표시 개선
  HowManySet/App/Coordinator/MyPageCoordinator.swift
Labels: 기능 구현, 오류 개선

#256 Feature/#249 - 루틴페이지에서 새운동 추가 기능 구현
  HowManySet/App/Coordinator/EditRoutineCoordinator.swift
  HowManySet/Data/Firestore/FirestoreService.swift
  HowManySet/Data/PersistentStorages/RealmService.swift
  HowManySet/Data/Repositories/RoutineRepositoryImpl.swift
  HowManySet/Presentation/Feature/EditExercise/EditExerciseView/EditExerciseViewController.swift
  HowManySet/Presentation/Feature/EditExercise/EditExerciseView/Reactor/EditExerciseViewReactor.swift
  HowManySet/Presentation/Feature/EditRoutine/EditRoutineTableFooterView.swift
  HowManySet/Presentation/Feature/EditRoutine/EditRoutineTableView.swift
  HowManySet/Presentation/Feature/EditRoutine/EditRoutineViewController.swift
  HowManySet/Presentation/Feature/EditRoutine/Reactor/EditRoutineViewReactor.swift
Labels: 기능 구현

#261 Loading Indicator 추가 / 닉네임 초기값 노출 이슈 해결
  HowManySet/Presentation/Feature/EditExercise/AddExerciseView/AddExerciseViewController.swift
  HowManySet/Presentation/Feature/EditExercise/EditExerciseView/EditExerciseViewController.swift
  HowManySet/Presentation/Feature/MyPage/MyPageViewController.swift
  HowManySet/Presentation/Feature/MyPage/Reactor/MyPageViewReactor.swift
  HowManySet/Presentation/Feature/RoutineList/Reactor/RoutineListViewReactor.swift
  HowManySet/Presentation/Feature/RoutineList/RoutineListViewController.swift
  HowManySet/Presentation/Services/LoadingIndicator.swift
Labels: 변경사항, 기능 구현

#268 운동 중 운동 편집 기능 구현
  HowManySet/App/Coordinator/HomeCoordinator.swift
  HowManySet/Domain/Entity/HomeEntity/WorkoutCardState.swift
  HowManySet/Domain/Entity/HomeEntity/WorkoutStateForEdit.swift
  HowManySet/Presentation/Feature/EditExercise/EditExerciseView/EditExerciseViewController.swift
  HowManySet/Presentation/Feature/Home/HomePagingCardView.swift
  HowManySet/Presentation/Feature/Home/HomeViewController.swift
  HowManySet/Presentation/Feature/Home/Reactor/HomeViewReactor.swift
Labels: 기능 구현

#273 LiveActivity 운동 시작 초기 딜레이 개선
  HowManySet/Presentation/Feature/Home/HomeViewController.swift
  HowManySetWidget/HowManySetWidgetLiveActivity.swift
Labels: bug, 오류 개선

#276 운동 완료 후 공유 시 이미지 공유
  HowManySet/Presentation/Feature/RoutineComplete/RoutineCompleteViewController.swift
Labels: 변경사항, 기능 구현

#281 온보딩 화면 스와이프 기능 추가
  HowManySet/Presentation/Feature/OnBoarding/OnBoardingViewController.swift
  HowManySet/Presentation/Feature/OnBoarding/OnboardingPageControlView.swift
  HowManySet/Presentation/Feature/OnBoarding/OnboardingView.swift
  HowManySet/Presentation/Feature/OnBoarding/Reactor/OnBoardingViewReactor.swift
Labels: 변경사항, 기능 구현

#284 LiveActivity 초기화면 오류
  HowManySet/Presentation/Feature/Home/HomeViewController.swift
  HowManySetWidget/HowManySetWidgetLiveActivity.swift
  LiveActivity/LiveActivityService.swift
Labels: bug, 리팩토링/구조화

#289 모든 세트 한번에 변경 추가, 0값 허용, 기본 세트 수 5
  HowManySet/Presentation/Feature/EditExercise/AddExerciseView/AddExerciseViewController.swift
  HowManySet/Presentation/Feature/EditExercise/AddExerciseView/Reactor/AddExerciseViewReactor.swift
  HowManySet/Presentation/Feature/EditExercise/EditExerciseContentView/EditExerciseContentView.swift
  HowManySet/Presentation/Feature/EditExercise/EditExerciseView/EditExerciseViewController.swift
  HowManySet/Presentation/Feature/EditExercise/EditExerciseView/Reactor/EditExerciseViewReactor.swift
  HowManySet/Presentation/Feature/Home/HomeViewController.swift
Labels: 변경사항, 기능 구현

#292 홈 화면 UI 개선, 운동 시작 모달에서 루틴 생성
  HowManySet/App/Coordinator/HomeCoordinator.swift
  HowManySet/App/Coordinator/RoutineListCoordinator.swift
  HowManySet/Presentation/Feature/Home/HomeViewController.swift
  HowManySet/Presentation/Feature/HomeStart/HomeStartViewController.swift
  HowManySet/Presentation/Feature/RoutineList/RoutineListView.swift
  HowManySet/Presentation/Feature/RoutineList/RoutineListViewController.swift
  HowManySet/Presentation/Feature/RoutineName/RoutineNameViewController.swift
  HowManySetWidget/HowManySetWidgetLiveActivity.swift
Labels: 변경사항, 기능 구현

#294 백그라운드에서 포그라운드 도입 시 휴식시간이 급격히 줄어드는 버그 해결
  HowManySet/Presentation/Feature/Home/HomeViewController.swift
  HowManySet/Presentation/Feature/Home/Reactor/HomeViewReactor.swift
Labels: bug

#316 Feature/#306 - HomeVC/Reactor 파일 분리 및 리팩토링
  HowManySet/Presentation/Feature/Home/HomeView.swift
  HowManySet/Presentation/Feature/Home/HomeViewController.swift
  HowManySet/Presentation/Feature/Home/Reactor/HomeViewReactor+Extension.swift
  HowManySet/Presentation/Feature/Home/Reactor/HomeViewReactor.swift
Labels: 오류 개선, 리팩토링/구조화

#320 Feature/#288 - FirestoreService와 프로토콜 리팩토링
  HowManySet/Data/Firestore/FirestoreDataType.swift
  HowManySet/Data/Firestore/FirestoreService.swift
  HowManySet/Data/Firestore/FirestoreServiceProtocol.swift
  HowManySet/Data/Repositories/RecordRepositoryImpl.swift
  HowManySet/Data/Repositories/RoutineRepositoryImpl.swift
  HowManySet/Data/Repositories/WorkoutRepositoryImpl.swift
Labels: 리팩토링/구조화

#321 Feature/#311 - 이름 길어질 경우 "..."요약 / 버튼 애니메이션 추가 / .0 -> 정수로 표시 / 텍스트필드 자리수 제한 / 분 숫자 표시 / Calendar RecordCell 색상 변경
  HowManySet/Presentation/Common/DefaultPopupViewController.swift
  HowManySet/Presentation/Common/ExercisePopupViewController.swift
  HowManySet/Presentation/Common/Extension/Int+Extension.swift
  HowManySet/Presentation/Feature/Calendar/CalendarViewController.swift
  HowManySet/Presentation/Feature/Calendar/RecordCell.swift
  HowManySet/Presentation/Feature/EditExercise/EditExerciseContentView/EditExerciseHorizontalContentStackView.swift
  HowManySet/Presentation/Feature/EditExercise/EditExerciseCurrentView/SavedExerciseView.swift
  HowManySet/Presentation/Feature/EditRoutine/EditRoutineTableView.swift
  HowManySet/Presentation/Feature/Home/HomeViewController.swift
  HowManySet/Presentation/Feature/OnBoarding/OnBoardingViewController.swift
  HowManySet/Presentation/Feature/RecordDetail/RecordDetailHeaderView.swift
  HowManySet/Presentation/Feature/RecordDetail/RecordDetailViewController.swift
  HowManySet/Presentation/Feature/RoutineComplete/RoutineCompleteViewController.swift
  HowManySet/Presentation/Feature/RoutineList/RoutineListViewController.swift
  HowManySet/Resources/Localizable/Localizable.xcstrings
Labels: 변경사항
